site_name: KAIA - Killer AI Agents
site_description: A modular, extensible platform for creating, managing, and interacting with AI agents
site_author: Mithran Mohanraj
site_url: https://example.com/killeraiagent
repo_url: https://github.com/username/killeraiagent
repo_name: killeraiagent

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Getting Started: usage/getting-started.md
    - LLM Management: usage/llm-management.md
    - Hardware Optimization: usage/hardware-optimization.md
    - LlamaSearch Integration: usage/llamasearch-integration.md
  - API Reference:
    - KAIA: api/kaia.md
    - Model: api/model.md
    - Resources: api/resources.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_if_no_docstring: false
            heading_level: 2
            docstring_section_style: spacy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/username/killeraiagent